title : Fimero
tagline: Open Source Software
author :
  name : Norman Kabir
  email : nkabir@gmail.com
  github : nkabir
  twitter : nkabir
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
samples:
  - samples/global.md
  - samples/grids.md
  - samples/fluid-grids.md
  - samples/layouts.md
  - samples/responsive.md
  - samples/typography.md
  - samples/code.md
  - samples/tables.md
  - samples/forms.md
  - samples/buttons.md
  - samples/images.md
  - samples/icons.md
  - samples/snippets.md
    
