title : Praxis
tagline: For the things I'm doing
author :
  name : Norman Kabir
  email : nkabir@gmail.com
  github : nkabir
  twitter : nkabir

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
