title : Fimero
tagline: Open Source Software
author :
  name : Norman Kabir
  email : nkabir@gmail.com
  github : nkabir
  twitter : nkabir
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
samples:
  indexes:
    - samples/scaffolding/index.md
    - samples/base/index.md
    - samples/components/index.md
  scaffolding:
    - samples/scaffolding/globals.md
    - samples/scaffolding/grids.md
    - samples/scaffolding/fluid-grids.md
    - samples/scaffolding/layouts.md
    - samples/scaffolding/responsive-layouts.md
  base:
    - samples/base/typography.md
    - samples/base/code.md
    - samples/base/tables.md
    - samples/base/forms.md
    - samples/base/buttons.md
    - samples/base/images.md
    - samples/base/icons.md
    - samples/base/snippets.md
  components:
    - samples/components/dropdowns.md
    - samples/components/button-groups.md
    - samples/components/button-dropdowns.md
    - samples/components/navs.md
    - samples/components/navsbars.md
    - samples/components/breadcrumbs.md
    - samples/components/pagination.md
    - samples/components/labels-badges.md
    - samples/components/typography.md
    - samples/components/thumbnails.md
    - samples/components/alerts.md
    - samples/components/progress-bars.md
    - samples/components/miscellaneous.md
